version: "3.7"
services:
  users:
    image: users
    container_name: users
    restart: always
    build:
      context: ./api
      dockerfile: ./deployment/users/Dockerfile
    depends_on:
      - db-users
    ports:
      - "3200:3200"
  db-users:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname users
    volumes:
      - mariadb_data-users:/var/lib/mysql

  qr-codes:
    image: qr-codes
    container_name: qr-codes
    build:
      context: ./api
      dockerfile: ./deployment/qr-codes/Dockerfile
    ports:
      - "3201:3201"

  invites:
    image: invites
    container_name: invites
    restart: always
    build:
      context: ./api
      dockerfile: ./deployment/invites/Dockerfile
    depends_on:
      - db-invites
    ports:
      - "3202:3202"
  db-invites:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname invites
    volumes:
      - mariadb_data-invites:/var/lib/mysql

  adminer:
    image: adminer:4-standalone
    ports:
      - 9001:8080

volumes:
  mariadb_data-users:
  mariadb_data-invites:


