version: "3.7"
services:
  users:
    image: users
    container_name: users
    build:
      context: ./api/users
      dockerfile: Dockerfile
    depends_on:
      - db-users
    ports:
      - "3200:3200"
  db-users:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname users
    volumes:
      - mariadb_data-users:/var/lib/mysql
  
  invites:
    image: invites
    container_name: invites
    build:
      context: ./api/invites
      dockerfile: Dockerfile
    ports:
      - "3201:3201"
  db-invites:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname invites
    volumes:
      - mariadb_data-invites:/var/lib/mysql

  qr-codes:
    image: qr-codes
    container_name: qr-codes
    build:
      context: ./api/qr-codes
      dockerfile: Dockerfile
    ports:
      - "3202:3202"
  db-qr-codes:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname qr-codes
    volumes:
      - mariadb_data-qr-codes:/var/lib/mysql

  adminer:
    image: adminer:4-standalone
    ports:
      - 9001:8080

volumes:
  mariadb_data-users:
  mariadb_data-invites:
  mariadb_data-qr-codes:


