version: "3.7"
services:
  users:
    image: users
    container_name: users
    build:
      context: ./api/users
      dockerfile: Dockerfile
    ports:
      - "3200:3200"

  adminer:
    image: adminer:4-standalone
    ports:
      - 9001:8080

  db-users:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname users
    volumes:
      - mariadb_data-users:/var/lib/mysql

volumes:
  mariadb_data-users:


